arch:
  - amd64
  - ppc64le
  
language: go
sudo: false
services:
  - redis-server

go:
  - 1.13
  - 1.14
  - 1.15
  - tip

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
